site_name: origins-kombo Documentation
nav:
    - Home: index.md
    - How to use:
      - Applying the key combo system: how_to_use/applying_the_key_combo_system.md
      - Registering a key or multiple keys: how_to_use/registering_a_key_or_multiple_keys.md
      - Adding your own kombo: how_to_use/adding_your_own_kombo.md
theme:
    name: readthedocs
    highlightjs: True
    prev_next_buttons_location: none
    titles_only: True
markdown_extensions:
    - toc:
        permalink: True
        separator: '_'
    - admonition
    - sane_lists
    - codehilite